"""
Export WRAI-Micro (1.25M) to INT8 Quantized C Engine for ESP32
Outputs:
1. wrai_micro_weights.bin (Contiguous INT8 Binary Payload)
2. wrai_micro_weights.h (C Header for PROGMEM Direct Compilation)
3. wrai_micro_vocab.h (C String Dictionary for On-Device Text Decoding)
"""

import os
import sys
import json
import struct
import numpy as np
import torch

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = os.path.dirname(__file__)
MODEL_PATH = os.path.join(BASE_DIR, "wrai_micro_1.25m_transplanted.pt")
TOKENIZER_PATH = os.path.join(BASE_DIR, "base_model", "tokenizer.json")

print("=" * 65, flush=True)
print(" [EXPORT] WRAI-MICRO (1.25M) C EXPORTER & INT8 QUANTIZER FOR ESP32", flush=True)
print("=" * 65, flush=True)

if not os.path.exists(MODEL_PATH):
    print(f"[ERR] Model checkpoint not found at {MODEL_PATH}.", flush=True)
    sys.exit(1)

# 1. Load Checkpoint
print("[*] Loading PyTorch checkpoint...", flush=True)
state_dict = torch.load(MODEL_PATH, map_location="cpu")

# 2. Build Quantized Binary
print("[*] Quantizing weights to INT8 with row-wise scaling...", flush=True)

bin_bytes = bytearray()
header_magic = 0x57524149 # "WRAI"
version = 1
vocab_size = 4023
hidden_dim = 128
num_layers = 4
num_heads = 4
head_dim = 32
ffn_dim = 341

# Header: 32 bytes
bin_bytes.extend(struct.pack("<IIIIIIII", header_magic, version, vocab_size, hidden_dim, num_layers, num_heads, head_dim, ffn_dim))

def pack_tensor_int8(tensor):
    t_np = tensor.float().numpy()
    scale = float(np.max(np.abs(t_np)) / 127.0)
    if scale == 0:
        scale = 1.0
    q = np.clip(np.round(t_np / scale), -127, 127).astype(np.int8)
    scale_bytes = struct.pack("<f", scale)
    return scale_bytes + q.tobytes()

def pack_tensor_fp32(tensor):
    return tensor.float().numpy().tobytes()

# Pack Embed Tokens (Shape: 4023 x 128)
print(" Packing embed_tokens (4023 x 128)...", flush=True)
bin_bytes.extend(pack_tensor_int8(state_dict["embed_tokens.weight"]))

# Pack Layers
for l in range(num_layers):
    print(f" Packing layer {l}...", flush=True)
    bin_bytes.extend(pack_tensor_fp32(state_dict[f"layers.{l}.input_layernorm.weight"]))
    
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.retention.q_proj.weight"]))
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.retention.k_proj.weight"]))
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.retention.v_proj.weight"]))
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.retention.r_proj.weight"]))
    
    bin_bytes.extend(pack_tensor_fp32(state_dict[f"layers.{l}.retention.gn.weight"]))
    bin_bytes.extend(pack_tensor_fp32(state_dict[f"layers.{l}.retention.gn.bias"]))
    
    gamma_decay = torch.sigmoid(state_dict[f"layers.{l}.retention.decay_param"])
    bin_bytes.extend(pack_tensor_fp32(gamma_decay))
    
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.retention.out_proj.weight"]))
    
    bin_bytes.extend(pack_tensor_fp32(state_dict[f"layers.{l}.post_attention_layernorm.weight"]))
    
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.mlp.gate_proj.weight"]))
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.mlp.up_proj.weight"]))
    bin_bytes.extend(pack_tensor_int8(state_dict[f"layers.{l}.mlp.down_proj.weight"]))

# Final Norm (FP32)
print(" Packing final norm...", flush=True)
bin_bytes.extend(pack_tensor_fp32(state_dict["norm.weight"]))

# Save binary file
out_bin = os.path.join(BASE_DIR, "wrai_micro_weights.bin")
with open(out_bin, "wb") as f:
    f.write(bin_bytes)

total_kb = len(bin_bytes) / 1024
total_mb = total_kb / 1024
print(f"[OK] Binary weights saved to: {out_bin} ({total_kb:.1f} KB / {total_mb:.2f} MB)")

# 3. Export C Vocab Table (Exact 4023 Tokens)
print("[*] Exporting Tokenizer Vocab Table to C header...", flush=True)
with open(TOKENIZER_PATH, "r", encoding="utf-8") as f:
    tok_data = json.load(f)

vocab_dict = tok_data.get("model", {}).get("vocab", {})
sorted_tokens = [""] * 4023
for token_str, token_id in vocab_dict.items():
    if token_id < 4023:
        escaped = token_str.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")
        sorted_tokens[token_id] = escaped

sorted_tokens[4019] = "<s>"
sorted_tokens[4020] = "</s>"
sorted_tokens[4021] = "<unk>"
sorted_tokens[4022] = "<pad>"

out_vocab_h = os.path.join(BASE_DIR, "wrai_micro_vocab.h")
with open(out_vocab_h, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by export_to_c.py for ESP32 WRAI-Micro\n")
    f.write("#ifndef WRAI_MICRO_VOCAB_H\n#define WRAI_MICRO_VOCAB_H\n\n")
    f.write("#include <pgmspace.h>\n\n")
    f.write(f"#define WRAI_VOCAB_SIZE 4023\n\n")
    f.write("const char* const WRAI_VOCAB[] PROGMEM = {\n")
    for i, tok in enumerate(sorted_tokens):
        f.write(f'  "{tok}", // {i}\n')
    f.write("};\n\n#endif // WRAI_MICRO_VOCAB_H\n")

print(f"[OK] Vocab table saved to: {out_vocab_h} (4023 tokens)")
print("[SUCCESS] C Export Complete!")
print("=" * 65, flush=True)
