#!/usr/bin/env python3
"""
WRAI Q15 Sine/Cosine LUT Generator
Generates pre-computed Q15 fixed-point Trigonometric Look-Up Tables for bare-metal C.
No third-party dependencies required.
"""

import math
import os
import sys

LUT_SIZE = 512
OUTPUT_HEADER = os.path.join(os.path.dirname(__file__), "..", "include", "wrai_lut.h")

def float_to_q15(val: float) -> int:
    scaled = round(val * 32768.0)
    if scaled > 32767:
        return 32767
    if scaled < -32768:
        return -32768
    return scaled

def main():
    sin_q15 = []
    cos_q15 = []

    for i in range(LUT_SIZE):
        angle = (2.0 * math.pi * i) / LUT_SIZE
        s_val = math.sin(angle)
        c_val = math.cos(angle)
        sin_q15.append(float_to_q15(s_val))
        cos_q15.append(float_to_q15(c_val))

    os.makedirs(os.path.dirname(os.path.abspath(OUTPUT_HEADER)), exist_ok=True)

    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write("/**\n")
        f.write(" * @file wrai_lut.h\n")
        f.write(" * @brief Pre-computed Q15 Sine and Cosine Look-Up Tables (512 Entries).\n")
        f.write(" * AUTO-GENERATED BY tools/generate_lut.py - DO NOT MODIFY MANUALLY.\n")
        f.write(" */\n\n")
        f.write("#ifndef WRAI_LUT_H\n")
        f.write("#define WRAI_LUT_H\n\n")
        f.write('#include "wrai_types.h"\n\n')
        f.write("#ifdef __cplusplus\n")
        f.write('extern "C" {\n')
        f.write("#endif\n\n")

        # Sine LUT array
        f.write("/** Sine Look-Up Table (Q15) */\n")
        f.write(f"static const q15_t g_wrai_sin_lut[{LUT_SIZE}] = {{\n")
        for i in range(0, LUT_SIZE, 8):
            chunk = sin_q15[i:i+8]
            formatted_chunk = ", ".join(f"{v:6d}" for v in chunk)
            f.write(f"    {formatted_chunk},\n")
        f.write("};\n\n")

        # Cosine LUT array
        f.write("/** Cosine Look-Up Table (Q15) */\n")
        f.write(f"static const q15_t g_wrai_cos_lut[{LUT_SIZE}] = {{\n")
        for i in range(0, LUT_SIZE, 8):
            chunk = cos_q15[i:i+8]
            formatted_chunk = ", ".join(f"{v:6d}" for v in chunk)
            f.write(f"    {formatted_chunk},\n")
        f.write("};\n\n")

        # Helper Inline Functions
        f.write("/** Fast Q15 Sine Lookup from LUT (Index masked to LUT_SIZE) */\n")
        f.write("static inline q15_t wrai_lut_sin(uint32_t phase_idx) {\n")
        f.write("    return g_wrai_sin_lut[phase_idx & WRAI_LUT_MASK];\n")
        f.write("}\n\n")

        f.write("/** Fast Q15 Cosine Lookup from LUT (Index masked to LUT_SIZE) */\n")
        f.write("static inline q15_t wrai_lut_cos(uint32_t phase_idx) {\n")
        f.write("    return g_wrai_cos_lut[phase_idx & WRAI_LUT_MASK];\n")
        f.write("}\n\n")

        f.write("#ifdef __cplusplus\n")
        f.write("}\n")
        f.write("#endif\n\n")
        f.write("#endif /* WRAI_LUT_H */\n")

    print(f"[OK] Generated {LUT_SIZE}-point Q15 Sine/Cosine LUT at: {os.path.abspath(OUTPUT_HEADER)}")

if __name__ == "__main__":
    main()
